name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "refactor"
  - title: "📝 Documentation"
    labels:
      - "docs"
  - title: "🔧 Dependencies"
    labels:
      - "deps"
      - "dependencies"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "fix"
      - "bugfix"
      - "chore"
      - "refactor"
  default: patch

exclude-labels:
  - "skip-changelog"
