name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
tag-prefix: ""
include-labels:
  - "feature"
  - "enhancement"
  - "fix"
  - "bugfix"
  - "chore"
  - "docs"
  - "refactor"
  - "dependencies"

categories:
  - title: "🚀 Features"
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "refactor"
  - title: "📝 Documentation"
    labels:
      - "docs"
  - title: "🔧 Dependencies"
    labels:
      - "deps"
      - "dependencies"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

template: |
  ## What's Changed
  $CHANGES

  ## 🚀 Features

  $CHANGES_FEATURES

  ## 🐛 Bug Fixes

  $CHANGES_BUGFIXES

  ## 🧰 Maintenance

  $CHANGES_MAINTENANCE

  ## 📝 Documentation

  $CHANGES_DOCUMENTATION

  ## 🔧 Dependencies

  $CHANGES_DEPENDENCIES

  ## Contributors

  $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "fix"
      - "bugfix"
      - "chore"
      - "refactor"
  default: patch

exclude-labels:
  - "skip-changelog"

sort-by: "merged_at"
sort-direction: "ascending"
