# .readthedocs.yaml
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
    rust: "1.78"
  jobs:
    post_install:
      - pip install uv==0.5.2
      - uv venv
      - uv sync --group docs
      - uv run pip install -e ./py-ih-muse

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false
