# .readthedocs.yaml
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
    rust: "1.78"
  commands:
    - pip install uv==0.5.2
    - uv venv
    - uv sync --group docs
    - uv run pip install -e ./py-ih-muse
    - ls -lR
    - pwd
    - ls -l
    - ls -l docs/
    - uv run python -m sphinx -T -b html -d _build/doctrees -D language=en -c docs/ docs/ _build/html

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false
