site_name: ih-muse
repo_url: https://github.com/infinitehaiku/ih-muse
site_url: https://infinitehaiku.github.io/ih-muse
site_description: Common muse library for python
site_author: Luis Diaz
edit_uri: edit/main/docs/
repo_name: infinitehaiku/ih-muse
copyright: Maintained by <a href="https://infinitehaiku.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [ih_muse]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/infinitehaiku/ih-muse
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ih-muse

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - optionalConfig.js
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - extra-loader.js
