name: "Setup Environment"
description: "Set up Python and Rust environment"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.12"
  uv-version:
    description: "uv version to use"
    required: true
    default: "0.4.6"
  rust-version:
    description: "Rust toolchain version"
    required: false
    default: "stable"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust-version }}
        components: rustfmt, clippy

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: "true"
        cache-suffix: ${{ matrix.python-version }}

    - name: Install cargo-hack
      uses: taiki-e/install-action@cargo-hack
      if: ${{ inputs.rust-version != '' }}

    - name: Install maturin
      run: pip install maturin
      shell: bash

    - name: Install Python dependencies
      run: uv sync --frozen
      shell: bash
