name: "🐞 Bug Report"
description: Report a bug in IH-Muse
labels: [bug, needs triage]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I have checked that this issue has not already been reported.
          required: true
        - label: I have confirmed this bug exists on the latest version.
          required: true

  - type: textarea
    id: example
    attributes:
      label: Reproducible Example
      description: Please provide a minimal example that reproduces the bug
      value: |
        ```python
        # For Python
        ```
        ```rust
        // For Rust
        ```
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of IH-Muse are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true
