name: "✨ Feature request"
description: Suggest a new feature or enhancement for IH-Muse.
labels: [enhancement]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Describe the feature or enhancement and explain why it should be implemented.
        Include an example if applicable.
    validations:
      required: true
