name: Main CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install dependencies and pre-commit hooks
        run: |
          uv run make install

      - name: Run code quality checks
        run: |
          uv run make check

  tests-and-type-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        rust-version: ["stable"]
        exclude:
          - os: windows-latest
            python-version: "3.13"
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          irm https://astral.sh/uv/install.ps1 | iex
          echo "$HOME/.cargo/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install uv
        if: runner.os != 'Windows'
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        shell: bash
        env:
          UV_LINK_MODE: copy
        run: |
          uv run make install

      - name: Build and install the package with maturin
        run: |
          uv run make develop

      - name: Run tests
        run: |
          uv run make test

      - name: Run typing checks with mypy
        if: ${{ matrix.python-version >= '3.10' }}
        run: |
          uv run mypy

      - name: Upload coverage reports to Codecov (Python 3.11 on Ubuntu only)
        uses: codecov/codecov-action@v4
        if: ${{ matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest' }}

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build documentation
        run: |
          uv run make docs-build
