name: Main CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: "3.11"
          rust-version: "stable"

      - name: Build Rust extension with maturin
        run: uv run maturin develop -m py-ih-muse/Cargo.toml

      - name: Run code quality checks
        run: make check

      - name: Run Rust formatting check
        run: cargo fmt --all -- --check

      - name: Run Rust linter with clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  tests-and-type-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        rust-version: ["stable"]
        exclude:
          - os: windows-latest
            python-version: "3.13"
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}
          rust-version: ${{ matrix.rust-version }}

      - name: Build and install the package with maturin
        run: uv run maturin develop -m py-ih-muse/Cargo.toml

      - name: Run Python tests with coverage
        run: uv run pytest tests --cov=ih_muse --cov-report=xml

      - name: Run typing checks with mypy
        run: uv run mypy py-ih-muse
        if: ${{ matrix.python-version != '3.12' }}

      - name: Upload coverage reports to Codecov (Python 3.11 on Ubuntu only)
        uses: codecov/codecov-action@v4
        if: ${{ matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest' }}

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: "3.11"
          rust-version: "stable"

      - name: Build Rust extension with maturin
        run: uv run maturin develop -m py-ih-muse/Cargo.toml

      - name: Validate documentation build
        run: uv run mkdocs build -s
