name: PR Labeler

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: PR Labeler
        uses: iantrich/pull-request-labeler@v2
        with:
          configuration-path: .github/pr-labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
