name: PR Labeler

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: PR Labeler
        uses: actions/labeler@v5
        with:
          configuration-path: .github/pr-labels.yml
