name: Release

on:
  push:
    branches:
      - main

jobs:
  rust-release:
    name: Rust Release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.check-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # Check if there is a parent commit
      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "::set-output name=sha::$(git rev-parse --verify --quiet HEAD^)"

      # Version detection (you might want to adapt this for Rust)
      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2.0.1
        with:
          version-command: |
            cargo metadata --format-version 1 | jq -r '.packages[0].version'

      # Publish ih-muse package
      - name: Publish main Rust package
        if: steps.check-version.outputs.tag
        run: |
          cd crates/ih-muse
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

  python-release:
    name: Python Release
    needs: rust-release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.7"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.0
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Build package
        run: poetry build --ansi

      # Only publish to PyPI if Rust release created a tag
      - name: Publish package on PyPI
        if: needs.rust-release.outputs.release_created
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

      # Publish to TestPyPI if no tag was created
      - name: Publish package on TestPyPI
        if: ${{ !needs.rust-release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5.23.0
        with:
          publish: ${{ needs.rust-release.outputs.release_created != '' }}
          tag: ${{ needs.rust-release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
