name: Release Python

on:
  push:
    branches:
      - main
    paths:
      - "crates/**"
      - "docs/**"
      - "py-ih-muse/**"
      - "Cargo.toml"

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  PYTHON_VERSION: "3.9"
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  create-sdist:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Create source distribution
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: >
            --manifest-path py-ih-muse/Cargo.toml
            --out dist

      - name: Test sdist
        run: |
          pip install --force-reinstall --verbose dist/*.tar.gz
          python -c 'import polars'

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist-ih-muse
          path: dist/*.tar.gz

  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]
        architecture: [x86-64]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          command: build
          target: ${{ steps.target.outputs.target }}
          args: >
            --profile dist-release
            --manifest-path py-ih-muse/Cargo.toml
            --out dist

      - name: Test wheel
        # Only test on x86-64 for now as this matches the runner architecture
        if: matrix.architecture == 'x86-64'
        run: |
          pip install --force-reinstall --verbose dist/*.whl
          python -c 'import ih_muse'

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.package }}-${{ matrix.os }}-${{ matrix.architecture }}
          path: dist/*.whl

  publish-to-pypi:
    needs: [create-sdist, build-wheels]
    environment:
      name: release-python
      url: https://pypi.org/project/ih-muse
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download sdists and wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        if: inputs.dry-run == false
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

  # publish-to-github:
  #   needs: publish-to-pypi
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repository
  #       uses: actions/checkout@v4

  #     - name: Download sdist
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: sdist-ih-muse
  #         path: dist

  #     - name: Get version from main Cargo.toml
  #       id: version
  #       run: |
  #         VERSION=$(grep -m 1 -oP 'version = "\K[^"]+' Cargo.toml)
  #         if [[ "$VERSION" == *"-"* ]]; then
  #           IS_PRERELEASE=true
  #         else
  #           IS_PRERELEASE=false
  #         fi
  #         echo "version=$VERSION" >> $GITHUB_OUTPUT
  #         echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT

  #     - name: Create GitHub release
  #       id: github-release
  #       uses: release-drafter/release-drafter@v6
  #       with:
  #         config-name: release-drafter-python.yml
  #         name: Python Polars ${{ steps.version.outputs.version }}
  #         tag: py-${{ steps.version.outputs.version }}
  #         version: ${{ steps.version.outputs.version }}
  #         prerelease: ${{ steps.version.outputs.is_prerelease }}
  #         disable-autolabeler: true
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Upload sdist to GitHub release
  #       run: gh release upload $TAG $FILES --clobber
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         TAG: ${{ steps.github-release.outputs.tag_name }}
  #         FILES: dist/ih-muse-*.tar.gz

  #     - name: Publish GitHub release
  #       if: inputs.dry-run == false
  #       run: gh release edit $TAG --draft=false
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         TAG: ${{ steps.github-release.outputs.tag_name }}

  #     - name: Trigger other workflows related to the release
  #       if: inputs.dry-run == false
  #       uses: peter-evans/repository-dispatch@v3
  #       with:
  #         event-type: python-release
  #         client-payload: >
  #           {
  #             "version": "${{ steps.version.outputs.version }}",
  #             "is_prerelease": "${{ steps.version.outputs.is_prerelease }}",
  #             "tag": "${{ steps.github-release.outputs.tag_name }}",
  #             "sha": "${{ inputs.sha || github.sha }}"
  #           }
